-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\untitled\Guassian_Filter.vhd
-- Created: 2025-01-31 22:05:47
-- 
-- Generated by MATLAB 9.11 and HDL Coder 3.19
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 1e-08
-- Target subsystem base rate: 1e-08
-- 
-- 
-- Clock Enable  Sample Time
-- -------------------------------------------------------------
-- ce_out        1e-08
-- -------------------------------------------------------------
-- 
-- 
-- Output Signal                 Clock Enable  Sample Time
-- -------------------------------------------------------------
-- Guassian                      ce_out        1e-08
-- -------------------------------------------------------------
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Guassian_Filter
-- Source Path: untitled/Subsystem2/Guassian Filter
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY Guassian_Filter IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        clk_enable                        :   IN    std_logic;
        Input                             :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
        ce_out                            :   OUT   std_logic;
        Guassian                          :   OUT   std_logic_vector(15 DOWNTO 0)  -- uint16
        );
END Guassian_Filter;


ARCHITECTURE rtl OF Guassian_Filter IS

  -- Signals
  SIGNAL enb                              : std_logic;
  SIGNAL Input_unsigned                   : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Gain_out1                        : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Delay24_out1                     : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Delay_out1                       : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Gain1_cast                       : unsigned(15 DOWNTO 0);  -- ufix16_En5
  SIGNAL Gain1_out1                       : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Delay25_out1                     : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Add_out1                         : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Delay61_out1                     : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Delay1_out1                      : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Gain2_mul_temp                   : unsigned(15 DOWNTO 0);  -- ufix16_En5
  SIGNAL Gain2_out1                       : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Delay26_out1                     : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Delay2_out1                      : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Gain3_cast                       : unsigned(15 DOWNTO 0);  -- ufix16_En5
  SIGNAL Gain3_out1                       : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Delay27_out1                     : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Add2_out1                        : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Delay60_out1                     : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Add1_out1                        : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Delay63_out1                     : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Delay3_out1                      : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Gain4_out1                       : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Delay28_out1                     : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Delay4_out1                      : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Gain5_cast                       : unsigned(15 DOWNTO 0);  -- ufix16_En5
  SIGNAL Gain5_out1                       : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Delay29_out1                     : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Add4_out1                        : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Delay59_out1                     : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Delay5_out1                      : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Gain6_cast                       : unsigned(15 DOWNTO 0);  -- ufix16_En3
  SIGNAL Gain6_out1                       : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Delay30_out1                     : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Delay6_out1                      : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Gain7_mul_temp                   : unsigned(15 DOWNTO 0);  -- ufix16_En3
  SIGNAL Gain7_out1                       : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Delay31_out1                     : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Add6_out1                        : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Delay58_out1                     : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Add5_out1                        : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Delay64_out1                     : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Add3_out1                        : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Delay69_out1                     : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Delay7_out1                      : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Gain8_cast                       : unsigned(15 DOWNTO 0);  -- ufix16_En3
  SIGNAL Gain8_out1                       : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Delay32_out1                     : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Delay8_out1                      : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Gain9_cast                       : unsigned(15 DOWNTO 0);  -- ufix16_En5
  SIGNAL Gain9_out1                       : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Delay33_out1                     : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Add8_out1                        : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Delay57_out1                     : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Delay9_out1                      : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Gain10_mul_temp                  : unsigned(15 DOWNTO 0);  -- ufix16_En5
  SIGNAL Gain10_out1                      : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Delay34_out1                     : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Delay10_out1                     : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Gain11_mul_temp                  : unsigned(15 DOWNTO 0);  -- ufix16_En3
  SIGNAL Gain11_out1                      : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Delay35_out1                     : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Add10_out1                       : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Delay56_out1                     : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Add15_out1                       : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Delay65_out1                     : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Delay11_out1                     : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Gain12_mul_temp                  : unsigned(15 DOWNTO 0);  -- ufix16_En2
  SIGNAL Gain12_out1                      : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Delay36_out1                     : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Delay12_out1                     : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Gain13_mul_temp                  : unsigned(15 DOWNTO 0);  -- ufix16_En3
  SIGNAL Gain13_out1                      : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Delay37_out1                     : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Add12_out1                       : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Delay55_out1                     : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Delay13_out1                     : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Gain14_mul_temp                  : unsigned(15 DOWNTO 0);  -- ufix16_En5
  SIGNAL Gain14_out1                      : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Delay38_out1                     : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Delay18_out1                     : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Gain15_cast                      : unsigned(15 DOWNTO 0);  -- ufix16_En5
  SIGNAL Gain15_out1                      : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Delay39_out1                     : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Add14_out1                       : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Delay54_out1                     : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Add9_out1                        : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Delay66_out1                     : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Add7_out1                        : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Delay14_out1                     : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Gain16_cast                      : unsigned(15 DOWNTO 0);  -- ufix16_En3
  SIGNAL Gain16_out1                      : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Delay40_out1                     : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Delay15_out1                     : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Gain17_mul_temp                  : unsigned(15 DOWNTO 0);  -- ufix16_En3
  SIGNAL Gain17_out1                      : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Delay41_out1                     : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Add16_out1                       : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Delay53_out1                     : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Delay16_out1                     : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Gain18_cast                      : unsigned(15 DOWNTO 0);  -- ufix16_En3
  SIGNAL Gain18_out1                      : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Delay42_out1                     : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Delay17_out1                     : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Gain19_cast                      : unsigned(15 DOWNTO 0);  -- ufix16_En5
  SIGNAL Gain19_out1                      : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Delay43_out1                     : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Add18_out1                       : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Delay52_out1                     : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Add21_out1                       : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Delay67_out1                     : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Delay23_out1                     : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Gain20_out1                      : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Delay44_out1                     : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Delay19_out1                     : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Gain21_cast                      : unsigned(15 DOWNTO 0);  -- ufix16_En5
  SIGNAL Gain21_out1                      : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Delay45_out1                     : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Add20_out1                       : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Delay51_out1                     : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Delay20_out1                     : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Gain22_mul_temp                  : unsigned(15 DOWNTO 0);  -- ufix16_En5
  SIGNAL Gain22_out1                      : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Delay46_out1                     : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Delay21_out1                     : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Gain23_cast                      : unsigned(15 DOWNTO 0);  -- ufix16_En5
  SIGNAL Gain23_out1                      : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Delay47_out1                     : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Add22_out1                       : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Delay50_out1                     : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Add17_out1                       : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Delay68_out1                     : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Add11_out1                       : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Delay71_out1                     : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Delay22_out1                     : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Gain24_out1                      : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Delay48_out1                     : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Delay49_out1                     : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Delay62_out1                     : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Delay70_out1                     : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Add13_out1                       : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Delay72_out1                     : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Add19_out1                       : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Add23_out1                       : unsigned(15 DOWNTO 0);  -- uint16

BEGIN
  Input_unsigned <= unsigned(Input);

  Gain_out1 <= resize(Input_unsigned, 16);

  enb <= clk_enable;

  Delay24_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay24_out1 <= to_unsigned(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay24_out1 <= Gain_out1;
      END IF;
    END IF;
  END PROCESS Delay24_process;


  Delay_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay_out1 <= to_unsigned(16#00#, 8);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay_out1 <= Input_unsigned;
      END IF;
    END IF;
  END PROCESS Delay_process;


  Gain1_cast <= resize(Delay_out1 & '0' & '0' & '0' & '0' & '0' & '0' & '0', 16);
  Gain1_out1 <= resize(Gain1_cast(15 DOWNTO 5), 16);

  Delay25_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay25_out1 <= to_unsigned(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay25_out1 <= Gain1_out1;
      END IF;
    END IF;
  END PROCESS Delay25_process;


  Add_out1 <= Delay24_out1 + Delay25_out1;

  Delay61_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay61_out1 <= to_unsigned(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay61_out1 <= Add_out1;
      END IF;
    END IF;
  END PROCESS Delay61_process;


  Delay1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay1_out1 <= to_unsigned(16#00#, 8);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay1_out1 <= Delay_out1;
      END IF;
    END IF;
  END PROCESS Delay1_process;


  Gain2_mul_temp <= to_unsigned(16#E0#, 8) * Delay1_out1;
  Gain2_out1 <= resize(Gain2_mul_temp(15 DOWNTO 5), 16);

  Delay26_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay26_out1 <= to_unsigned(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay26_out1 <= Gain2_out1;
      END IF;
    END IF;
  END PROCESS Delay26_process;


  Delay2_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay2_out1 <= to_unsigned(16#00#, 8);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay2_out1 <= Delay1_out1;
      END IF;
    END IF;
  END PROCESS Delay2_process;


  Gain3_cast <= resize(Delay2_out1 & '0' & '0' & '0' & '0' & '0' & '0' & '0', 16);
  Gain3_out1 <= resize(Gain3_cast(15 DOWNTO 5), 16);

  Delay27_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay27_out1 <= to_unsigned(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay27_out1 <= Gain3_out1;
      END IF;
    END IF;
  END PROCESS Delay27_process;


  Add2_out1 <= Delay26_out1 + Delay27_out1;

  Delay60_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay60_out1 <= to_unsigned(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay60_out1 <= Add2_out1;
      END IF;
    END IF;
  END PROCESS Delay60_process;


  Add1_out1 <= Delay61_out1 + Delay60_out1;

  Delay63_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay63_out1 <= to_unsigned(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay63_out1 <= Add1_out1;
      END IF;
    END IF;
  END PROCESS Delay63_process;


  Delay3_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay3_out1 <= to_unsigned(16#00#, 8);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay3_out1 <= Delay2_out1;
      END IF;
    END IF;
  END PROCESS Delay3_process;


  Gain4_out1 <= resize(Delay3_out1, 16);

  Delay28_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay28_out1 <= to_unsigned(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay28_out1 <= Gain4_out1;
      END IF;
    END IF;
  END PROCESS Delay28_process;


  Delay4_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay4_out1 <= to_unsigned(16#00#, 8);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay4_out1 <= Delay3_out1;
      END IF;
    END IF;
  END PROCESS Delay4_process;


  Gain5_cast <= resize(Delay4_out1 & '0' & '0' & '0' & '0' & '0' & '0' & '0', 16);
  Gain5_out1 <= resize(Gain5_cast(15 DOWNTO 5), 16);

  Delay29_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay29_out1 <= to_unsigned(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay29_out1 <= Gain5_out1;
      END IF;
    END IF;
  END PROCESS Delay29_process;


  Add4_out1 <= Delay28_out1 + Delay29_out1;

  Delay59_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay59_out1 <= to_unsigned(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay59_out1 <= Add4_out1;
      END IF;
    END IF;
  END PROCESS Delay59_process;


  Delay5_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay5_out1 <= to_unsigned(16#00#, 8);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay5_out1 <= Delay4_out1;
      END IF;
    END IF;
  END PROCESS Delay5_process;


  Gain6_cast <= resize(Delay5_out1 & '0' & '0' & '0' & '0' & '0' & '0' & '0', 16);
  Gain6_out1 <= resize(Gain6_cast(15 DOWNTO 3), 16);

  Delay30_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay30_out1 <= to_unsigned(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay30_out1 <= Gain6_out1;
      END IF;
    END IF;
  END PROCESS Delay30_process;


  Delay6_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay6_out1 <= to_unsigned(16#00#, 8);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay6_out1 <= Delay5_out1;
      END IF;
    END IF;
  END PROCESS Delay6_process;


  Gain7_mul_temp <= to_unsigned(16#D0#, 8) * Delay6_out1;
  Gain7_out1 <= resize(Gain7_mul_temp(15 DOWNTO 3), 16);

  Delay31_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay31_out1 <= to_unsigned(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay31_out1 <= Gain7_out1;
      END IF;
    END IF;
  END PROCESS Delay31_process;


  Add6_out1 <= Delay30_out1 + Delay31_out1;

  Delay58_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay58_out1 <= to_unsigned(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay58_out1 <= Add6_out1;
      END IF;
    END IF;
  END PROCESS Delay58_process;


  Add5_out1 <= Delay59_out1 + Delay58_out1;

  Delay64_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay64_out1 <= to_unsigned(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay64_out1 <= Add5_out1;
      END IF;
    END IF;
  END PROCESS Delay64_process;


  Add3_out1 <= Delay63_out1 + Delay64_out1;

  Delay69_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay69_out1 <= to_unsigned(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay69_out1 <= Add3_out1;
      END IF;
    END IF;
  END PROCESS Delay69_process;


  Delay7_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay7_out1 <= to_unsigned(16#00#, 8);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay7_out1 <= Delay6_out1;
      END IF;
    END IF;
  END PROCESS Delay7_process;


  Gain8_cast <= resize(Delay7_out1 & '0' & '0' & '0' & '0' & '0' & '0' & '0', 16);
  Gain8_out1 <= resize(Gain8_cast(15 DOWNTO 3), 16);

  Delay32_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay32_out1 <= to_unsigned(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay32_out1 <= Gain8_out1;
      END IF;
    END IF;
  END PROCESS Delay32_process;


  Delay8_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay8_out1 <= to_unsigned(16#00#, 8);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay8_out1 <= Delay7_out1;
      END IF;
    END IF;
  END PROCESS Delay8_process;


  Gain9_cast <= resize(Delay8_out1 & '0' & '0' & '0' & '0' & '0' & '0' & '0', 16);
  Gain9_out1 <= resize(Gain9_cast(15 DOWNTO 5), 16);

  Delay33_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay33_out1 <= to_unsigned(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay33_out1 <= Gain9_out1;
      END IF;
    END IF;
  END PROCESS Delay33_process;


  Add8_out1 <= Delay32_out1 + Delay33_out1;

  Delay57_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay57_out1 <= to_unsigned(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay57_out1 <= Add8_out1;
      END IF;
    END IF;
  END PROCESS Delay57_process;


  Delay9_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay9_out1 <= to_unsigned(16#00#, 8);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay9_out1 <= Delay8_out1;
      END IF;
    END IF;
  END PROCESS Delay9_process;


  Gain10_mul_temp <= to_unsigned(16#E0#, 8) * Delay9_out1;
  Gain10_out1 <= resize(Gain10_mul_temp(15 DOWNTO 5), 16);

  Delay34_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay34_out1 <= to_unsigned(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay34_out1 <= Gain10_out1;
      END IF;
    END IF;
  END PROCESS Delay34_process;


  Delay10_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay10_out1 <= to_unsigned(16#00#, 8);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay10_out1 <= Delay9_out1;
      END IF;
    END IF;
  END PROCESS Delay10_process;


  Gain11_mul_temp <= to_unsigned(16#D0#, 8) * Delay10_out1;
  Gain11_out1 <= resize(Gain11_mul_temp(15 DOWNTO 3), 16);

  Delay35_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay35_out1 <= to_unsigned(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay35_out1 <= Gain11_out1;
      END IF;
    END IF;
  END PROCESS Delay35_process;


  Add10_out1 <= Delay34_out1 + Delay35_out1;

  Delay56_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay56_out1 <= to_unsigned(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay56_out1 <= Add10_out1;
      END IF;
    END IF;
  END PROCESS Delay56_process;


  Add15_out1 <= Delay57_out1 + Delay56_out1;

  Delay65_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay65_out1 <= to_unsigned(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay65_out1 <= Add15_out1;
      END IF;
    END IF;
  END PROCESS Delay65_process;


  Delay11_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay11_out1 <= to_unsigned(16#00#, 8);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay11_out1 <= Delay10_out1;
      END IF;
    END IF;
  END PROCESS Delay11_process;


  Gain12_mul_temp <= to_unsigned(16#A4#, 8) * Delay11_out1;
  Gain12_out1 <= resize(Gain12_mul_temp(15 DOWNTO 2), 16);

  Delay36_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay36_out1 <= to_unsigned(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay36_out1 <= Gain12_out1;
      END IF;
    END IF;
  END PROCESS Delay36_process;


  Delay12_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay12_out1 <= to_unsigned(16#00#, 8);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay12_out1 <= Delay11_out1;
      END IF;
    END IF;
  END PROCESS Delay12_process;


  Gain13_mul_temp <= to_unsigned(16#D0#, 8) * Delay12_out1;
  Gain13_out1 <= resize(Gain13_mul_temp(15 DOWNTO 3), 16);

  Delay37_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay37_out1 <= to_unsigned(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay37_out1 <= Gain13_out1;
      END IF;
    END IF;
  END PROCESS Delay37_process;


  Add12_out1 <= Delay36_out1 + Delay37_out1;

  Delay55_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay55_out1 <= to_unsigned(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay55_out1 <= Add12_out1;
      END IF;
    END IF;
  END PROCESS Delay55_process;


  Delay13_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay13_out1 <= to_unsigned(16#00#, 8);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay13_out1 <= Delay12_out1;
      END IF;
    END IF;
  END PROCESS Delay13_process;


  Gain14_mul_temp <= to_unsigned(16#E0#, 8) * Delay13_out1;
  Gain14_out1 <= resize(Gain14_mul_temp(15 DOWNTO 5), 16);

  Delay38_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay38_out1 <= to_unsigned(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay38_out1 <= Gain14_out1;
      END IF;
    END IF;
  END PROCESS Delay38_process;


  Delay18_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay18_out1 <= to_unsigned(16#00#, 8);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay18_out1 <= Delay13_out1;
      END IF;
    END IF;
  END PROCESS Delay18_process;


  Gain15_cast <= resize(Delay18_out1 & '0' & '0' & '0' & '0' & '0' & '0' & '0', 16);
  Gain15_out1 <= resize(Gain15_cast(15 DOWNTO 5), 16);

  Delay39_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay39_out1 <= to_unsigned(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay39_out1 <= Gain15_out1;
      END IF;
    END IF;
  END PROCESS Delay39_process;


  Add14_out1 <= Delay38_out1 + Delay39_out1;

  Delay54_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay54_out1 <= to_unsigned(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay54_out1 <= Add14_out1;
      END IF;
    END IF;
  END PROCESS Delay54_process;


  Add9_out1 <= Delay55_out1 + Delay54_out1;

  Delay66_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay66_out1 <= to_unsigned(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay66_out1 <= Add9_out1;
      END IF;
    END IF;
  END PROCESS Delay66_process;


  Add7_out1 <= Delay65_out1 + Delay66_out1;

  Delay14_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay14_out1 <= to_unsigned(16#00#, 8);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay14_out1 <= Delay18_out1;
      END IF;
    END IF;
  END PROCESS Delay14_process;


  Gain16_cast <= resize(Delay14_out1 & '0' & '0' & '0' & '0' & '0' & '0' & '0', 16);
  Gain16_out1 <= resize(Gain16_cast(15 DOWNTO 3), 16);

  Delay40_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay40_out1 <= to_unsigned(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay40_out1 <= Gain16_out1;
      END IF;
    END IF;
  END PROCESS Delay40_process;


  Delay15_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay15_out1 <= to_unsigned(16#00#, 8);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay15_out1 <= Delay14_out1;
      END IF;
    END IF;
  END PROCESS Delay15_process;


  Gain17_mul_temp <= to_unsigned(16#D0#, 8) * Delay15_out1;
  Gain17_out1 <= resize(Gain17_mul_temp(15 DOWNTO 3), 16);

  Delay41_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay41_out1 <= to_unsigned(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay41_out1 <= Gain17_out1;
      END IF;
    END IF;
  END PROCESS Delay41_process;


  Add16_out1 <= Delay40_out1 + Delay41_out1;

  Delay53_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay53_out1 <= to_unsigned(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay53_out1 <= Add16_out1;
      END IF;
    END IF;
  END PROCESS Delay53_process;


  Delay16_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay16_out1 <= to_unsigned(16#00#, 8);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay16_out1 <= Delay15_out1;
      END IF;
    END IF;
  END PROCESS Delay16_process;


  Gain18_cast <= resize(Delay16_out1 & '0' & '0' & '0' & '0' & '0' & '0' & '0', 16);
  Gain18_out1 <= resize(Gain18_cast(15 DOWNTO 3), 16);

  Delay42_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay42_out1 <= to_unsigned(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay42_out1 <= Gain18_out1;
      END IF;
    END IF;
  END PROCESS Delay42_process;


  Delay17_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay17_out1 <= to_unsigned(16#00#, 8);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay17_out1 <= Delay16_out1;
      END IF;
    END IF;
  END PROCESS Delay17_process;


  Gain19_cast <= resize(Delay17_out1 & '0' & '0' & '0' & '0' & '0' & '0' & '0', 16);
  Gain19_out1 <= resize(Gain19_cast(15 DOWNTO 5), 16);

  Delay43_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay43_out1 <= to_unsigned(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay43_out1 <= Gain19_out1;
      END IF;
    END IF;
  END PROCESS Delay43_process;


  Add18_out1 <= Delay42_out1 + Delay43_out1;

  Delay52_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay52_out1 <= to_unsigned(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay52_out1 <= Add18_out1;
      END IF;
    END IF;
  END PROCESS Delay52_process;


  Add21_out1 <= Delay53_out1 + Delay52_out1;

  Delay67_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay67_out1 <= to_unsigned(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay67_out1 <= Add21_out1;
      END IF;
    END IF;
  END PROCESS Delay67_process;


  Delay23_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay23_out1 <= to_unsigned(16#00#, 8);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay23_out1 <= Delay17_out1;
      END IF;
    END IF;
  END PROCESS Delay23_process;


  Gain20_out1 <= resize(Delay23_out1, 16);

  Delay44_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay44_out1 <= to_unsigned(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay44_out1 <= Gain20_out1;
      END IF;
    END IF;
  END PROCESS Delay44_process;


  Delay19_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay19_out1 <= to_unsigned(16#00#, 8);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay19_out1 <= Delay23_out1;
      END IF;
    END IF;
  END PROCESS Delay19_process;


  Gain21_cast <= resize(Delay19_out1 & '0' & '0' & '0' & '0' & '0' & '0' & '0', 16);
  Gain21_out1 <= resize(Gain21_cast(15 DOWNTO 5), 16);

  Delay45_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay45_out1 <= to_unsigned(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay45_out1 <= Gain21_out1;
      END IF;
    END IF;
  END PROCESS Delay45_process;


  Add20_out1 <= Delay44_out1 + Delay45_out1;

  Delay51_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay51_out1 <= to_unsigned(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay51_out1 <= Add20_out1;
      END IF;
    END IF;
  END PROCESS Delay51_process;


  Delay20_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay20_out1 <= to_unsigned(16#00#, 8);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay20_out1 <= Delay19_out1;
      END IF;
    END IF;
  END PROCESS Delay20_process;


  Gain22_mul_temp <= to_unsigned(16#E0#, 8) * Delay20_out1;
  Gain22_out1 <= resize(Gain22_mul_temp(15 DOWNTO 5), 16);

  Delay46_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay46_out1 <= to_unsigned(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay46_out1 <= Gain22_out1;
      END IF;
    END IF;
  END PROCESS Delay46_process;


  Delay21_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay21_out1 <= to_unsigned(16#00#, 8);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay21_out1 <= Delay20_out1;
      END IF;
    END IF;
  END PROCESS Delay21_process;


  Gain23_cast <= resize(Delay21_out1 & '0' & '0' & '0' & '0' & '0' & '0' & '0', 16);
  Gain23_out1 <= resize(Gain23_cast(15 DOWNTO 5), 16);

  Delay47_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay47_out1 <= to_unsigned(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay47_out1 <= Gain23_out1;
      END IF;
    END IF;
  END PROCESS Delay47_process;


  Add22_out1 <= Delay46_out1 + Delay47_out1;

  Delay50_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay50_out1 <= to_unsigned(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay50_out1 <= Add22_out1;
      END IF;
    END IF;
  END PROCESS Delay50_process;


  Add17_out1 <= Delay51_out1 + Delay50_out1;

  Delay68_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay68_out1 <= to_unsigned(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay68_out1 <= Add17_out1;
      END IF;
    END IF;
  END PROCESS Delay68_process;


  Add11_out1 <= Delay67_out1 + Delay68_out1;

  Delay71_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay71_out1 <= to_unsigned(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay71_out1 <= Add11_out1;
      END IF;
    END IF;
  END PROCESS Delay71_process;


  Delay22_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay22_out1 <= to_unsigned(16#00#, 8);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay22_out1 <= Delay21_out1;
      END IF;
    END IF;
  END PROCESS Delay22_process;


  Gain24_out1 <= resize(Delay22_out1, 16);

  Delay48_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay48_out1 <= to_unsigned(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay48_out1 <= Gain24_out1;
      END IF;
    END IF;
  END PROCESS Delay48_process;


  Delay49_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay49_out1 <= to_unsigned(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay49_out1 <= Delay48_out1;
      END IF;
    END IF;
  END PROCESS Delay49_process;


  Delay62_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay62_out1 <= to_unsigned(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay62_out1 <= Delay49_out1;
      END IF;
    END IF;
  END PROCESS Delay62_process;


  Delay70_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay70_out1 <= to_unsigned(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay70_out1 <= Add7_out1;
      END IF;
    END IF;
  END PROCESS Delay70_process;


  Add13_out1 <= Delay69_out1 + Delay70_out1;

  Delay72_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay72_out1 <= to_unsigned(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay72_out1 <= Delay62_out1;
      END IF;
    END IF;
  END PROCESS Delay72_process;


  Add19_out1 <= Delay71_out1 + Delay72_out1;

  Add23_out1 <= Add13_out1 + Add19_out1;

  Guassian <= std_logic_vector(Add23_out1);

  ce_out <= clk_enable;

END rtl;

