-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc2\untitled\G_abs.vhd
-- Created: 2025-01-31 22:14:19
-- 
-- Generated by MATLAB 9.11 and HDL Coder 3.19
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: G_abs
-- Source Path: untitled/Subsystem3/G abs
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY G_abs IS
  PORT( Out_Sobel_X                       :   IN    std_logic_vector(15 DOWNTO 0);  -- int16
        Out_Sobel_Y                       :   IN    std_logic_vector(15 DOWNTO 0);  -- int16
        G_abs_1                           :   OUT   std_logic_vector(15 DOWNTO 0)  -- int16
        );
END G_abs;


ARCHITECTURE rtl OF G_abs IS

  -- Signals
  SIGNAL Out_Sobel_X_signed               : signed(15 DOWNTO 0);  -- int16
  SIGNAL Abs_y                            : signed(16 DOWNTO 0);  -- sfix17
  SIGNAL Abs_out1                         : signed(15 DOWNTO 0);  -- int16
  SIGNAL Out_Sobel_Y_signed               : signed(15 DOWNTO 0);  -- int16
  SIGNAL Abs1_y                           : signed(16 DOWNTO 0);  -- sfix17
  SIGNAL Abs1_out1                        : signed(15 DOWNTO 0);  -- int16
  SIGNAL Add_out1                         : signed(15 DOWNTO 0);  -- int16

BEGIN
  Out_Sobel_X_signed <= signed(Out_Sobel_X);

  
  Abs_y <=  - (resize(Out_Sobel_X_signed, 17)) WHEN Out_Sobel_X_signed < to_signed(16#0000#, 16) ELSE
      resize(Out_Sobel_X_signed, 17);
  Abs_out1 <= Abs_y(15 DOWNTO 0);

  Out_Sobel_Y_signed <= signed(Out_Sobel_Y);

  
  Abs1_y <=  - (resize(Out_Sobel_Y_signed, 17)) WHEN Out_Sobel_Y_signed < to_signed(16#0000#, 16) ELSE
      resize(Out_Sobel_Y_signed, 17);
  Abs1_out1 <= Abs1_y(15 DOWNTO 0);

  Add_out1 <= Abs_out1 + Abs1_out1;

  G_abs_1 <= std_logic_vector(Add_out1);

END rtl;

