-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc2\untitled\Sobel_X.vhd
-- Created: 2025-01-31 22:14:19
-- 
-- Generated by MATLAB 9.11 and HDL Coder 3.19
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Sobel_X
-- Source Path: untitled/Subsystem3/Sobel X
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY Sobel_X IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        Input                             :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
        Gx                                :   OUT   std_logic_vector(15 DOWNTO 0)  -- int16
        );
END Sobel_X;


ARCHITECTURE rtl OF Sobel_X IS

  -- Signals
  SIGNAL Input_unsigned                   : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Gain_cast                        : signed(8 DOWNTO 0);  -- sfix9
  SIGNAL Gain_out1                        : signed(15 DOWNTO 0);  -- int16
  SIGNAL Delay24_out1                     : signed(15 DOWNTO 0);  -- int16
  SIGNAL Delay_out1                       : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Gain1_out1                       : signed(15 DOWNTO 0);  -- int16
  SIGNAL Delay25_out1                     : signed(15 DOWNTO 0);  -- int16
  SIGNAL Add_out1                         : signed(15 DOWNTO 0);  -- int16
  SIGNAL Delay61_out1                     : signed(15 DOWNTO 0);  -- int16
  SIGNAL Delay1_out1                      : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Gain2_out1                       : signed(15 DOWNTO 0);  -- int16
  SIGNAL Delay26_out1                     : signed(15 DOWNTO 0);  -- int16
  SIGNAL Delay2_out1                      : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Gain3_cast                       : signed(8 DOWNTO 0);  -- sfix9
  SIGNAL Gain3_mul_temp                   : signed(24 DOWNTO 0);  -- sfix25
  SIGNAL Gain3_out1                       : signed(15 DOWNTO 0);  -- int16
  SIGNAL Delay27_out1                     : signed(15 DOWNTO 0);  -- int16
  SIGNAL Add2_out1                        : signed(15 DOWNTO 0);  -- int16
  SIGNAL Delay60_out1                     : signed(15 DOWNTO 0);  -- int16
  SIGNAL Add1_out1                        : signed(15 DOWNTO 0);  -- int16
  SIGNAL Delay63_out1                     : signed(15 DOWNTO 0);  -- int16
  SIGNAL Delay3_out1                      : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Gain4_out1                       : signed(15 DOWNTO 0);  -- int16
  SIGNAL Delay28_out1                     : signed(15 DOWNTO 0);  -- int16
  SIGNAL Delay4_out1                      : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Gain5_cast                       : unsigned(15 DOWNTO 0);  -- ufix16_En6
  SIGNAL Gain5_out1                       : signed(15 DOWNTO 0);  -- int16
  SIGNAL Delay29_out1                     : signed(15 DOWNTO 0);  -- int16
  SIGNAL Add4_out1                        : signed(15 DOWNTO 0);  -- int16
  SIGNAL Delay59_out1                     : signed(15 DOWNTO 0);  -- int16
  SIGNAL Delay5_out1                      : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Gain6_cast                       : signed(8 DOWNTO 0);  -- sfix9
  SIGNAL Gain6_out1                       : signed(15 DOWNTO 0);  -- int16
  SIGNAL Delay30_out1                     : signed(15 DOWNTO 0);  -- int16
  SIGNAL Delay6_out1                      : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Gain7_out1                       : signed(15 DOWNTO 0);  -- int16
  SIGNAL Delay31_out1                     : signed(15 DOWNTO 0);  -- int16
  SIGNAL Add6_out1                        : signed(15 DOWNTO 0);  -- int16
  SIGNAL Delay58_out1                     : signed(15 DOWNTO 0);  -- int16
  SIGNAL Add5_out1                        : signed(15 DOWNTO 0);  -- int16
  SIGNAL Delay64_out1                     : signed(15 DOWNTO 0);  -- int16
  SIGNAL Add3_out1                        : signed(15 DOWNTO 0);  -- int16
  SIGNAL Delay69_out1                     : signed(15 DOWNTO 0);  -- int16
  SIGNAL Delay7_out1                      : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Gain24_out1                      : signed(15 DOWNTO 0);  -- int16
  SIGNAL Delay48_out1                     : signed(15 DOWNTO 0);  -- int16
  SIGNAL Delay49_out1                     : signed(15 DOWNTO 0);  -- int16
  SIGNAL Delay62_out1                     : signed(15 DOWNTO 0);  -- int16
  SIGNAL Delay70_out1                     : signed(15 DOWNTO 0);  -- int16
  SIGNAL Add13_out1                       : signed(15 DOWNTO 0);  -- int16

BEGIN
  Input_unsigned <= unsigned(Input);

  Gain_cast <= signed(resize(Input_unsigned, 9));
  Gain_out1 <= resize( - (Gain_cast), 16);

  Delay24_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay24_out1 <= to_signed(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay24_out1 <= Gain_out1;
      END IF;
    END IF;
  END PROCESS Delay24_process;


  Delay_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay_out1 <= to_unsigned(16#00#, 8);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay_out1 <= Input_unsigned;
      END IF;
    END IF;
  END PROCESS Delay_process;


  Gain1_out1 <= to_signed(16#0000#, 16);

  Delay25_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay25_out1 <= to_signed(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay25_out1 <= Gain1_out1;
      END IF;
    END IF;
  END PROCESS Delay25_process;


  Add_out1 <= Delay24_out1 + Delay25_out1;

  Delay61_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay61_out1 <= to_signed(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay61_out1 <= Add_out1;
      END IF;
    END IF;
  END PROCESS Delay61_process;


  Delay1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay1_out1 <= to_unsigned(16#00#, 8);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay1_out1 <= Delay_out1;
      END IF;
    END IF;
  END PROCESS Delay1_process;


  Gain2_out1 <= signed(resize(Delay1_out1, 16));

  Delay26_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay26_out1 <= to_signed(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay26_out1 <= Gain2_out1;
      END IF;
    END IF;
  END PROCESS Delay26_process;


  Delay2_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay2_out1 <= to_unsigned(16#00#, 8);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay2_out1 <= Delay1_out1;
      END IF;
    END IF;
  END PROCESS Delay2_process;


  Gain3_cast <= signed(resize(Delay2_out1, 9));
  -- CSD Encoding (2) : 10; Cost (Adders) = 0
  Gain3_mul_temp <=  - (resize(Gain3_cast & '0', 25));
  Gain3_out1 <= Gain3_mul_temp(15 DOWNTO 0);

  Delay27_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay27_out1 <= to_signed(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay27_out1 <= Gain3_out1;
      END IF;
    END IF;
  END PROCESS Delay27_process;


  Add2_out1 <= Delay26_out1 + Delay27_out1;

  Delay60_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay60_out1 <= to_signed(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay60_out1 <= Add2_out1;
      END IF;
    END IF;
  END PROCESS Delay60_process;


  Add1_out1 <= Delay61_out1 + Delay60_out1;

  Delay63_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay63_out1 <= to_signed(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay63_out1 <= Add1_out1;
      END IF;
    END IF;
  END PROCESS Delay63_process;


  Delay3_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay3_out1 <= to_unsigned(16#00#, 8);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay3_out1 <= Delay2_out1;
      END IF;
    END IF;
  END PROCESS Delay3_process;


  Gain4_out1 <= to_signed(16#0000#, 16);

  Delay28_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay28_out1 <= to_signed(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay28_out1 <= Gain4_out1;
      END IF;
    END IF;
  END PROCESS Delay28_process;


  Delay4_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay4_out1 <= to_unsigned(16#00#, 8);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay4_out1 <= Delay3_out1;
      END IF;
    END IF;
  END PROCESS Delay4_process;


  Gain5_cast <= resize(Delay4_out1 & '0' & '0' & '0' & '0' & '0' & '0' & '0', 16);
  Gain5_out1 <= signed(resize(Gain5_cast(15 DOWNTO 6), 16));

  Delay29_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay29_out1 <= to_signed(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay29_out1 <= Gain5_out1;
      END IF;
    END IF;
  END PROCESS Delay29_process;


  Add4_out1 <= Delay28_out1 + Delay29_out1;

  Delay59_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay59_out1 <= to_signed(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay59_out1 <= Add4_out1;
      END IF;
    END IF;
  END PROCESS Delay59_process;


  Delay5_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay5_out1 <= to_unsigned(16#00#, 8);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay5_out1 <= Delay4_out1;
      END IF;
    END IF;
  END PROCESS Delay5_process;


  Gain6_cast <= signed(resize(Delay5_out1, 9));
  Gain6_out1 <= resize( - (Gain6_cast), 16);

  Delay30_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay30_out1 <= to_signed(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay30_out1 <= Gain6_out1;
      END IF;
    END IF;
  END PROCESS Delay30_process;


  Delay6_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay6_out1 <= to_unsigned(16#00#, 8);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay6_out1 <= Delay5_out1;
      END IF;
    END IF;
  END PROCESS Delay6_process;


  Gain7_out1 <= to_signed(16#0000#, 16);

  Delay31_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay31_out1 <= to_signed(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay31_out1 <= Gain7_out1;
      END IF;
    END IF;
  END PROCESS Delay31_process;


  Add6_out1 <= Delay30_out1 + Delay31_out1;

  Delay58_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay58_out1 <= to_signed(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay58_out1 <= Add6_out1;
      END IF;
    END IF;
  END PROCESS Delay58_process;


  Add5_out1 <= Delay59_out1 + Delay58_out1;

  Delay64_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay64_out1 <= to_signed(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay64_out1 <= Add5_out1;
      END IF;
    END IF;
  END PROCESS Delay64_process;


  Add3_out1 <= Delay63_out1 + Delay64_out1;

  Delay69_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay69_out1 <= to_signed(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay69_out1 <= Add3_out1;
      END IF;
    END IF;
  END PROCESS Delay69_process;


  Delay7_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay7_out1 <= to_unsigned(16#00#, 8);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay7_out1 <= Delay6_out1;
      END IF;
    END IF;
  END PROCESS Delay7_process;


  Gain24_out1 <= signed(resize(Delay7_out1, 16));

  Delay48_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay48_out1 <= to_signed(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay48_out1 <= Gain24_out1;
      END IF;
    END IF;
  END PROCESS Delay48_process;


  Delay49_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay49_out1 <= to_signed(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay49_out1 <= Delay48_out1;
      END IF;
    END IF;
  END PROCESS Delay49_process;


  Delay62_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay62_out1 <= to_signed(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay62_out1 <= Delay49_out1;
      END IF;
    END IF;
  END PROCESS Delay62_process;


  Delay70_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay70_out1 <= to_signed(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay70_out1 <= Delay62_out1;
      END IF;
    END IF;
  END PROCESS Delay70_process;


  Add13_out1 <= Delay69_out1 + Delay70_out1;

  Gx <= std_logic_vector(Add13_out1);

END rtl;

