-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc2\untitled\Subsystem3.vhd
-- Created: 2025-01-31 22:14:19
-- 
-- Generated by MATLAB 9.11 and HDL Coder 3.19
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 1e-08
-- Target subsystem base rate: 1e-08
-- 
-- 
-- Clock Enable  Sample Time
-- -------------------------------------------------------------
-- ce_out        1e-08
-- -------------------------------------------------------------
-- 
-- 
-- Output Signal                 Clock Enable  Sample Time
-- -------------------------------------------------------------
-- G_abs_1                       ce_out        1e-08
-- G_abs1                        ce_out        1e-08
-- G_abs2                        ce_out        1e-08
-- -------------------------------------------------------------
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Subsystem3
-- Source Path: untitled/Subsystem3
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY Subsystem3 IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        clk_enable                        :   IN    std_logic;
        Input                             :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
        ce_out                            :   OUT   std_logic;
        G_abs_1                           :   OUT   std_logic_vector(15 DOWNTO 0);  -- int16
        G_abs1                            :   OUT   std_logic_vector(15 DOWNTO 0);  -- int16
        G_abs2                            :   OUT   std_logic_vector(15 DOWNTO 0)  -- int16
        );
END Subsystem3;


ARCHITECTURE rtl OF Subsystem3 IS

  -- Component Declarations
  COMPONENT Sobel_X
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          Input                           :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
          Gx                              :   OUT   std_logic_vector(15 DOWNTO 0)  -- int16
          );
  END COMPONENT;

  COMPONENT Sobel_Y
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          Input                           :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
          Gy                              :   OUT   std_logic_vector(15 DOWNTO 0)  -- int16
          );
  END COMPONENT;

  COMPONENT G_abs
    PORT( Out_Sobel_X                     :   IN    std_logic_vector(15 DOWNTO 0);  -- int16
          Out_Sobel_Y                     :   IN    std_logic_vector(15 DOWNTO 0);  -- int16
          G_abs_1                         :   OUT   std_logic_vector(15 DOWNTO 0)  -- int16
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : Sobel_X
    USE ENTITY work.Sobel_X(rtl);

  FOR ALL : Sobel_Y
    USE ENTITY work.Sobel_Y(rtl);

  FOR ALL : G_abs
    USE ENTITY work.G_abs(rtl);

  -- Signals
  SIGNAL Sobel_X_out1                     : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL Sobel_Y_out1                     : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL G_abs_out1                       : std_logic_vector(15 DOWNTO 0);  -- ufix16

BEGIN
  u_Sobel_X : Sobel_X
    PORT MAP( clk => clk,
              reset => reset,
              enb => clk_enable,
              Input => Input,  -- uint8
              Gx => Sobel_X_out1  -- int16
              );

  u_Sobel_Y : Sobel_Y
    PORT MAP( clk => clk,
              reset => reset,
              enb => clk_enable,
              Input => Input,  -- uint8
              Gy => Sobel_Y_out1  -- int16
              );

  u_G_abs : G_abs
    PORT MAP( Out_Sobel_X => Sobel_X_out1,  -- int16
              Out_Sobel_Y => Sobel_Y_out1,  -- int16
              G_abs_1 => G_abs_out1  -- int16
              );

  ce_out <= clk_enable;

  G_abs_1 <= G_abs_out1;

  G_abs1 <= Sobel_X_out1;

  G_abs2 <= Sobel_Y_out1;

END rtl;

