webtalk_init -webtalk_dir D:/SBU/1/VHDL/Project/Code/CannyEdgeDetection/CannyEdgeDetection.sim/sim_1/behav/xsim/xsim.dir/wrapper_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Jan 30 22:30:19 2025" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2552052" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "5a38e80f-9ad5-43a7-a620-342566b08115" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "916724fa838c443c9d9219f6e7617343" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "14" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "12th Gen Intel(R) Core(TM) i7-12700H" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2688 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "10240 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "9.08_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "14460_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1459611720 -regid "" -xml D:/SBU/1/VHDL/Project/Code/CannyEdgeDetection/CannyEdgeDetection.sim/sim_1/behav/xsim/xsim.dir/wrapper_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html D:/SBU/1/VHDL/Project/Code/CannyEdgeDetection/CannyEdgeDetection.sim/sim_1/behav/xsim/xsim.dir/wrapper_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm D:/SBU/1/VHDL/Project/Code/CannyEdgeDetection/CannyEdgeDetection.sim/sim_1/behav/xsim/xsim.dir/wrapper_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
